// <auto-generated />
using System;
using Labb_3_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_3_API.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250421110048_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_3_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.svensson@example.com",
                            FirstName = "Anna",
                            LastName = "Svensson",
                            PhoneNumber = "070-1234567"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1985, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erik.karlsson@example.com",
                            FirstName = "Erik",
                            LastName = "Karlsson",
                            PhoneNumber = "073-9876543"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1998, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa.andersson@example.com",
                            FirstName = "Lisa",
                            LastName = "Andersson",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.PersonService", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PersonServices");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            PersonId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            PersonId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            PersonId = 3,
                            ServiceId = 3
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Intresserad av olika musikgenrer och artister.",
                            Title = "Musik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Följer och utövar olika sporter.",
                            Title = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fascinerad av den senaste tekniska utvecklingen.",
                            Title = "Teknologi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Älskar att upptäcka nya platser och kulturer.",
                            Title = "Resor"
                        });
                });

            modelBuilder.Entity("PersonService", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("PersonService");
                });

            modelBuilder.Entity("Labb_3_API.Models.PersonService", b =>
                {
                    b.HasOne("Labb_3_API.Models.Person", "Person")
                        .WithMany("PersonServices")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3_API.Models.Service", "Service")
                        .WithMany("PersonServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PersonService", b =>
                {
                    b.HasOne("Labb_3_API.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3_API.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb_3_API.Models.Person", b =>
                {
                    b.Navigation("PersonServices");
                });

            modelBuilder.Entity("Labb_3_API.Models.Service", b =>
                {
                    b.Navigation("PersonServices");
                });
#pragma warning restore 612, 618
        }
    }
}
