// <auto-generated />
using System;
using Labb_3_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_3_API.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250424094036_Rename Service to Intrest")]
    partial class RenameServicetoIntrest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_3_API.Models.Intrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Intrests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Intresserad av olika musikgenrer och artister.",
                            Title = "Musik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Följer och utövar olika sporter.",
                            Title = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fascinerad av den senaste tekniska utvecklingen.",
                            Title = "Teknologi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Älskar att upptäcka nya platser och kulturer.",
                            Title = "Resor"
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonIntrestId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonIntrestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PersonIntrestId = 1,
                            Title = "Länk 1",
                            Url = "https://example.com/link1"
                        },
                        new
                        {
                            Id = 2,
                            PersonIntrestId = 2,
                            Title = "Länk 2",
                            Url = "https://example.com/link2"
                        },
                        new
                        {
                            Id = 3,
                            PersonIntrestId = 3,
                            Title = "Länk 3",
                            Url = "https://example.com/link3"
                        },
                        new
                        {
                            Id = 4,
                            PersonIntrestId = 4,
                            Title = "Länk 4",
                            Url = "https://example.com/link4"
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.svensson@example.com",
                            FirstName = "Anna",
                            LastName = "Svensson",
                            PhoneNumber = "070-1234567"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1985, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erik.karlsson@example.com",
                            FirstName = "Erik",
                            LastName = "Karlsson",
                            PhoneNumber = "073-9876543"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1998, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa.andersson@example.com",
                            FirstName = "Lisa",
                            LastName = "Andersson",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.PersonIntrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntrestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntrestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonIntrests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IntrestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            IntrestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            IntrestId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            IntrestId = 3,
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("Labb_3_API.Models.Link", b =>
                {
                    b.HasOne("Labb_3_API.Models.PersonIntrest", "PersonIntrests")
                        .WithMany("Links")
                        .HasForeignKey("PersonIntrestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonIntrests");
                });

            modelBuilder.Entity("Labb_3_API.Models.PersonIntrest", b =>
                {
                    b.HasOne("Labb_3_API.Models.Intrest", "Intrest")
                        .WithMany("PersonIntrests")
                        .HasForeignKey("IntrestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_3_API.Models.Person", "Person")
                        .WithMany("PersonIntrests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intrest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb_3_API.Models.Intrest", b =>
                {
                    b.Navigation("PersonIntrests");
                });

            modelBuilder.Entity("Labb_3_API.Models.Person", b =>
                {
                    b.Navigation("PersonIntrests");
                });

            modelBuilder.Entity("Labb_3_API.Models.PersonIntrest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
